  const prompts = [
  "A futuristic city at sunset with flying cars",
  "A majestic dragon flying over snowy mountains",
  "A cyberpunk street glowing with neon lights",
  "A cozy cabin in the middle of a magical forest",
  "An astronaut relaxing on the moon with a campfire",
  "A giant whale swimming through the clouds",
  "A medieval castle surrounded by cherry blossom trees",
  "A realistic portrait of a lion wearing a royal crown",
  "A peaceful Japanese garden during autumn",
  "A pirate ship sailing through a storm at night",
  "A futuristic robot painting a masterpiece",
  "A tropical island with crystal-clear water",
  "A mysterious wizard casting spells in an ancient library",
  "A colorful underwater city full of sea creatures",
  "A cute corgi dressed as an astronaut",
  "A phoenix rising from glowing flames",
  "A modern luxury house on a cliff overlooking the ocean",
  "A fantasy village hidden inside giant mushrooms",
  "A black panther with glowing blue eyes",
  "A steampunk train traveling through the mountains",
  "A magical tree with glowing leaves at night",
  "A realistic tiger walking through a bamboo forest",
  "A space station orbiting Saturn",
  "A snowy owl flying under the northern lights",
  "A samurai standing in the rain with a glowing sword",
  "A dreamy lavender field under a starry sky",
  "A futuristic motorcycle racing through a neon tunnel",
  "A giant waterfall flowing into the clouds",
  "A golden retriever wearing sunglasses on the beach",
  "A fantasy kingdom floating in the sky",
  "A mystical crystal cave illuminated by glowing gems",
  "A superhero overlooking a futuristic skyline",
  "A beautiful peacock spreading colorful feathers",
  "A vintage coffee shop on a rainy evening",
  "A cute panda eating bamboo in a peaceful forest",
  "A realistic wolf howling at a full moon",
  "An enchanted bridge leading to another world",
  "A luxury sports car parked in Tokyo at night",
  "A magical unicorn in an enchanted forest",
  "A colorful hot air balloon festival at sunrise",
  "A futuristic AI assistant in a modern office",
  "A serene lake reflecting snowy mountains",
  "A majestic eagle soaring above the Grand Canyon",
  "A fantasy elf village hidden in giant trees",
  "A giant octopus attacking an old pirate ship",
  "A cozy reading room with floor-to-ceiling bookshelves",
  "A glowing jellyfish floating in deep space",
  "A cinematic desert with ancient ruins",
  "A realistic elephant walking through the African savanna",
  "A peaceful Zen temple in the mountains"
];
export default prompts